#
# Copyright INK Labs. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  ca.org1.example.com:
    image: zhigui/zigledger-ca
    environment:
      - ZIGLEDGER_CA_HOME=/etc/zigledger/zigledger-ca-server
      - ZIGLEDGER_CA_SERVER_CA_CERTFILE=/etc/zigledger/zigledger-ca-server-config/ca.org1.example.com-cert.pem
      - ZIGLEDGER_CA_SERVER_CA_KEYFILE=/etc/zigledger/zigledger-ca-server-config/bc2d0fe9b743c31cd823281f164dbb5b9f1035f03d784ea62061f5ded738c424_sk
      - ZIGLEDGER_CA_SERVER_TLS_ENABLED=true
      - ZIGLEDGER_CA_SERVER_TLS_CERTFILE=/etc/zigledger/zigledger-ca-server-config/ca.org1.example.com-cert.pem
      - ZIGLEDGER_CA_SERVER_TLS_KEYFILE=/etc/zigledger/zigledger-ca-server-config/bc2d0fe9b743c31cd823281f164dbb5b9f1035f03d784ea62061f5ded738c424_sk
    ports:
      - "7054:7054"
    command: sh -c 'zigledger-ca-server start -b admin:adminpw -d'
    volumes:
      - ../config/artifacts/channel/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/zigledger/zigledger-ca-server-config
    container_name: ca_peerOrg1

  ca.org2.example.com:
    image: zhigui/zigledger-ca
    environment:
      - ZIGLEDGER_CA_HOME=/etc/zigledger/zigledger-ca-server
      - ZIGLEDGER_CA_SERVER_CA_CERTFILE=/etc/zigledger/zigledger-ca-server-config/ca.org2.example.com-cert.pem
      - ZIGLEDGER_CA_SERVER_CA_KEYFILE=/etc/zigledger/zigledger-ca-server-config/6a332ee688c7f355b3e3ed1b53c987dac564c98becb0abbf0718fce607eea10a_sk
      - ZIGLEDGER_CA_SERVER_TLS_ENABLED=true
      - ZIGLEDGER_CA_SERVER_TLS_CERTFILE=/etc/zigledger/zigledger-ca-server-config/ca.org2.example.com-cert.pem
      - ZIGLEDGER_CA_SERVER_TLS_KEYFILE=/etc/zigledger/zigledger-ca-server-config/6a332ee688c7f355b3e3ed1b53c987dac564c98becb0abbf0718fce607eea10a_sk
    ports:
      - "8054:7054"
    command: sh -c 'zigledger-ca-server start -b admin:adminpw -d'
    volumes:
      - ../config/artifacts/channel/crypto-config/peerOrganizations/org2.example.com/ca/:/etc/zigledger/zigledger-ca-server-config
    container_name: ca_peerOrg2

  orderer.example.com:
    container_name: orderer.example.com
    image: zhigui/zigledger-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/zigledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/zigledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - GODEBUG=netdns=go
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/zigledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/zigledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/zigledger/crypto/orderer/tls/ca.crt, /etc/zigledger/crypto/peerOrg1/tls/ca.crt, /etc/zigledger/crypto/peerOrg2/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/zhigui/zigledger/orderers
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ../config/artifacts/channel:/etc/zigledger/configtx
        - ../config/artifacts/channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/zigledger/crypto/orderer
        - ../config/artifacts/channel/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/zigledger/crypto/peerOrg1
        - ../config/artifacts/channel/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/:/etc/zigledger/crypto/peerOrg2

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file:   peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ../config/artifacts/channel/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/zigledger/crypto/peer
    depends_on:
      - orderer.example.com

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    extends:
      file:   peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
        - ../config/artifacts/channel/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/:/etc/zigledger/crypto/peer
    depends_on:
      - orderer.example.com

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file:   peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - ../config/artifacts/channel/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/:/etc/zigledger/crypto/peer
    depends_on:
      - orderer.example.com

  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    extends:
      file:   peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.example.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
    ports:
      - 8056:7051
      - 8058:7053
    volumes:
        - ../config/artifacts/channel/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/:/etc/zigledger/crypto/peer
    depends_on:
      - orderer.example.com

  zigerface-mysql:
    container_name: zigerface-mysql
    image: zhigui/zigerface-mysql:x86_64-0.1.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=zhigui
    ports:
      - 3306:3306
    volumes:
      - /tmp/data/mysql/:/var/lib/mysql
      - ../config/db/explore.sql:/usr/local/work/explore.sql
      - ../config/db/init_peer.sql:/usr/local/work/init_peer.sql

  zigerface-fullserver.org1:
      container_name: zigerface-fullserver-org1
      image: zhigui/zigerface-fullserver:x86_64-0.1.6
      ports:
        - 8081:8081
      volumes:
        - ../config/artifacts:/work/config/artifacts
        - ../config/network-config.json:/work/config/network-config.json
#        - ../config/zigledger-client-kvs_peerOrg1:/tmp/zigledger-client-kvs_peerOrg1
        - ../config/config.json:/work/config/config.json
      links:
        - peer0.org1.example.com
        - peer1.org1.example.com
        - peer0.org2.example.com
        - peer1.org2.example.com
