version: '3.1'

services:
  zigerface-fullserver.org1:
      hostname: zigerface-fullserver.org1
      network_mode: "host"
      image: zhigui/zigerface-fullserver:x86_64-0.1.10
      ports:
        - 8081:8081
      volumes:
        - ./:/work/config/artifacts
        - ./network-config.json:/work/config/network-config.json
        - ./zigledger-client-kvs_peerOrg1:/tmp/zigledger-client-kvs_peerOrg1
        - ./config.json:/work/config/config.json