version: '3.1'

services:
  zookeeper1:
    image: zookeeper
    restart: always
    hostname: zookeeper1
    network_mode: "host"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper0:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper2:2888:3888