version: '3.1'

services:
  orderer1:
    hostname: orderer1.example.com
    container_name: orderer1
    network_mode: "host"
    image: zhigui/zigledger-orderer:x86_64-1.2.12
    environment:
      - ORDERER_GENERAL_LOGLEVEL=WARNING
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/zhigui/configtx/twoorgs.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/zhigui/msp/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_PROFILE_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/zhigui/msp/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/zhigui/msp/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/zhigui/msp/orderer/tls/ca.crt]
      - GODEBUG=netdns=go
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/zhigui/zigledger/orderer
    command: orderer
    ports:
      - 7050:7050
      - 6060:6060
    volumes:
        - ./:/etc/zhigui/configtx
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/:/etc/zhigui/msp/orderer
