version: '3.1'

services:

  ca5:
    image: zhigui/zigledger-ca:x86_64-1.1.1
    hostname: ca5
    network_mode: "host"
    environment:
      - ZIGLEDGER_CA_HOME=/etc/zhigui/fabric-ca-server
      - ZIGLEDGER_CA_SERVER_CA_NAME=ca-org6
      - ZIGLEDGER_CA_SERVER_CA_CERTFILE=/etc/zhigui/fabric-ca-server-config/ca.org6.example.com-cert.pem
      - ZIGLEDGER_CA_SERVER_CA_KEYFILE=/etc/zhigui/fabric-ca-server-config/9cb61790b97df219657c1e231d474b5b6e500046be0def50b5eeab5d75857764_sk
      - ZIGLEDGER_CA_SERVER_TLS_ENABLED=false
      - ZIGLEDGER_CA_SERVER_TLS_CERTFILE=/etc/zhigui/fabric-ca-server-config/ca.org6.example.com-cert.pem
      - ZIGLEDGER_CA_SERVER_TLS_KEYFILE=/etc/zhigui/fabric-ca-server-config/9cb61790b97df219657c1e231d474b5b6e500046be0def50b5eeab5d75857764_sk
      - GODEBUG=netdns=go
    ports:
      - "7054:7054"
    command: sh -c 'zigledger-ca-server start -b admin:adminpw -d'
    volumes:
      - ./ca:/etc/zhigui/zigledger-ca-server
      - ./ca:/etc/zhigui/fabric-ca-server
      - ./ca-config.yaml:/etc/zhigui/zigledger-ca-server/zigledger-ca-server-config.yaml
      - ./ca-config.yaml:/etc/zhigui/fabric-ca-server/zigledger-ca-server-config.yaml
      - ./crypto-config/peerOrganizations/org6.example.com/ca/:/etc/zhigui/fabric-ca-server-config