version: '3.1'

services:

  ca3:
    image: zhigui/zigledger-ca:x86_64-1.1.1
    hostname: ca3
    network_mode: "host"
    environment:
      - ZIGLEDGER_CA_HOME=/etc/zhigui/fabric-ca-server
      - ZIGLEDGER_CA_SERVER_CA_NAME=ca-org4
      - ZIGLEDGER_CA_SERVER_CA_CERTFILE=/etc/zhigui/fabric-ca-server-config/ca.org4.example.com-cert.pem
      - ZIGLEDGER_CA_SERVER_CA_KEYFILE=/etc/zhigui/fabric-ca-server-config/33f8afcece920e201e12f3313c22284fea9dbdd31474e0ffb5a762d7b6ece9fd_sk
      - ZIGLEDGER_CA_SERVER_TLS_ENABLED=false
      - ZIGLEDGER_CA_SERVER_TLS_CERTFILE=/etc/zhigui/fabric-ca-server-config/ca.org4.example.com-cert.pem
      - ZIGLEDGER_CA_SERVER_TLS_KEYFILE=/etc/zhigui/fabric-ca-server-config/33f8afcece920e201e12f3313c22284fea9dbdd31474e0ffb5a762d7b6ece9fd_sk
      - GODEBUG=netdns=go
    ports:
      - "7054:7054"
    command: sh -c 'zigledger-ca-server start -b admin:adminpw -d'
    volumes:
      - ./ca:/etc/zhigui/zigledger-ca-server
      - ./ca:/etc/zhigui/fabric-ca-server
      - ./ca-config.yaml:/etc/zhigui/zigledger-ca-server/zigledger-ca-server-config.yaml
      - ./ca-config.yaml:/etc/zhigui/fabric-ca-server/zigledger-ca-server-config.yaml
      - ./crypto-config/peerOrganizations/org4.example.com/ca/:/etc/zhigui/fabric-ca-server-config