version: '3.1'

services:
  peer0.org2.example.com:
    hostname: peer0.org2.example.com
    network_mode: "host"
    image: zhigui/zigledger-peer:x86_64-1.2.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/zhigui/msp/peer/msp/
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_SIMPLEFEEK=0
      - CORE_PEER_SIMPLEFEEX0=0
      - CORE_PEER_SIMPLEFEEB=0
      - CORE_PEER_TLS_KEY_FILE=/etc/zhigui/msp/peer/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/zhigui/msp/peer/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/zhigui/msp/peer/tls/ca.crt
      - GODEBUG=netdns=go
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
      - 6060:6060
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/:/etc/zhigui/msp/peer

  peer1.org2.example.com:
    hostname: peer1.org2.example.com
    image: zhigui/zigledger-peer:x86_64-1.2.4
    network_mode: "host"
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org2.example.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/zhigui/msp/peer/msp/
      - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_SIMPLEFEEK=0
      - CORE_PEER_SIMPLEFEEX0=0
      - CORE_PEER_SIMPLEFEEB=0
      - CORE_PEER_TLS_KEY_FILE=/etc/zhigui/msp/peer/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/zhigui/msp/peer/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/zhigui/msp/peer/tls/ca.crt
      - GODEBUG=netdns=go
    working_dir: /opt/gopath/src/github.com/zhigui/zigledger/peer
    command: peer node start
    ports:
      - 7057:7051
      - 7059:7053
      - 6061:6060
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/:/etc/zhigui/msp/peer

  ca1:
    image: zhigui/zigledger-ca:x86_64-1.1.1
    hostname: ca1
    network_mode: "host"
    environment:
      - ZIGLEDGER_CA_HOME=/etc/zhigui/fabric-ca-server
      - ZIGLEDGER_CA_SERVER_CA_NAME=ca-org2
      - ZIGLEDGER_CA_SERVER_CA_CERTFILE=/etc/zhigui/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - ZIGLEDGER_CA_SERVER_CA_KEYFILE=/etc/zhigui/fabric-ca-server-config/9a5cc4473f231ea68a66449cd64ed374ff9c794ef0ea918f291e3d90e248c5e7_sk
      - ZIGLEDGER_CA_SERVER_TLS_ENABLED=true
      - ZIGLEDGER_CA_SERVER_TLS_CERTFILE=/etc/zhigui/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - ZIGLEDGER_CA_SERVER_TLS_KEYFILE=/etc/zhigui/fabric-ca-server-config/9a5cc4473f231ea68a66449cd64ed374ff9c794ef0ea918f291e3d90e248c5e7_sk
      - GODEBUG=netdns=go
    ports:
      - "7054:7054"
    command: sh -c 'zigledger-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/zhigui/fabric-ca-server-config